# Generated by Django 3.1.1 on 2021-09-06 06:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_vax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphReport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=124), size=None)),
                ('vaccination_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=124), size=None)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('FAILURE', 'failure')], default='pending', max_length=124)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
