# Generated by Django 3.1.1 on 2021-09-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_vax', '0002_graphreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphreport',
            old_name='countries',
            new_name='locations',
        ),
    ]
