# Generated by Django 3.1.1 on 2021-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_vax', '0003_auto_20210906_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubvaxdata',
            name='iso_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='githubvaxdata',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
