# Generated by Django 3.1.1 on 2021-09-10 19:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_vax', '0004_auto_20210910_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubvaxdata',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='graphreport',
            name='intermediate_regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='graphreport',
            name='regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='graphreport',
            name='sub_regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='graphreport',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='graphreport',
            name='vaccination_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
