# Generated by Django 3.1.1 on 2021-09-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_vax', '0005_auto_20210910_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubvaxdata',
            options={},
        ),
    ]
