# Generated by Django 3.1.1 on 2021-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_vax', '0006_auto_20210910_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubvaxdata',
            name='intermediate_region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='githubvaxdata',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='githubvaxdata',
            name='sub_region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='githubvaxdata',
            name='total_boosters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubvaxdata',
            name='total_boosters_per_hundred',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
